### ISSUE TITLE
policy-webhook-certs secrets are not getting created

### ISSUE THREAD

**Issue by MageshSrinivasulu** [sigstore/policy-controller#41] opened 2022-06-17 10:33 UTC
Can someone please provide details on how these secrets are getting populated? I my case its not showing. webhook-certs are working fine 

**policy-webhook-certs :**

````
kubectl describe secret policy-webhook-certs
Name:         policy-webhook-certs
Labels:       app.kubernetes.io/instance=policy-controller
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=policy-controller
              app.kubernetes.io/version=1.9.0
              control-plane=policy-controller-policy-webhook
              helm.sh/chart=policy-controller-0.1.25
Annotations:  meta.helm.sh/release-name: policy-controller

Type:  Opaque

Data
====
````

**webhook-certs :**

```
kubectl describe secret webhook-certs
Name:         webhook-certs
Labels:       app.kubernetes.io/instance=policy-controller
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=policy-controller
              app.kubernetes.io/version=1.9.0
              control-plane=policy-controller-webhook
              helm.sh/chart=policy-controller-0.1.25
Annotations:  meta.helm.sh/release-name: policy-controller

Type:  Opaque

Data
====
server-cert.pem:  794 bytes
server-key.pem:   241 bytes
ca-cert.pem:      855 bytes
```

**Comment by hectorj2f** [comment] 2022-06-17 10:59
@MageshSrinivasulu could you explain how you install the code? I haven’t experienced the certificates issues when using ko to apply the code in main. 

On the other hand, the certificate generation is done via https://knative.dev/docs/serving/using-auto-tls/

**Comment by MageshSrinivasulu** [comment] 2022-06-17 11:09
@hectorj2f I am just performing helm install on this https://github.com/sigstore/helm-charts/tree/main/charts/policy-controller. I didn't make any specific changes to helm values

**Comment by hectorj2f** [comment] 2022-06-17 14:57
@MageshSrinivasulu i have faced this issue before we might be hitting a race condition. We will need to replicate it. Perhaps you could delete/install it again including the resources in that namespace. Are ypu installing it on kind ?

**Comment by hectorj2f** [comment] 2022-07-25 17:20
@MageshSrinivasulu I remember discussing with you this issue in our helm-charts repo. I am sharing a gist of it here https://github.com/sigstore/helm-charts/issues/217:

```
The certificates are not created because the leases (kubectl get leases) are not cleaned up for the webhooks. I managed to reproduce it by installing and deleting the chart.

I feel the solution could be one of these three:

* delete the namespace where you installed the policy-controller chart when uninstalling it, if possible.
* delete the leases before every re-installation.
* wait until the leases expire (approx. 10min after creation)
* create your own certs instead of relying on the auto-TLS
``

**Comment by hectorj2f** [comment] 2022-07-25 17:20
Closing the issue for now. Feel free to re-open it.

**Closed by hectorj2f** 2022-07-25 17:20 UTC
Labels: question

**Comment by gustavoromerobenitez** [comment] 2023-03-31 15:41
This issue is still present.  The policy-webhooks-certs secret contains no data and despite deleting the namespace and re-installing, the issue re-appears.

policy-controller AppVersion: 0.7.0
policy-controller Helm Chart version: 0.5.4
Kubernetes (GKE) version: 1.24.9-gke.3200
